"""
Knowledge Package Schema.
Data contract output from the Knowledge Engine (Qwen3-4B), designed specifically
for direct consumption by the Content Orchestrator and Generative LLM pipeline.
"""

from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field
from backend.app.schemas.intent import IntentAndPersonalization
from backend.app.schemas.semantic_document import EntityItem, ClaimItem, RelationshipItem


class EvidenceItem(BaseModel):
    """An atomic piece of retrieved evidence with source attribution."""
    chunk_id: str = Field(..., description="ID of the retrieved document chunk")
    element_id: Optional[str] = Field(default=None, description="Original semantic element ID")
    page: int = Field(..., ge=1, description="Page number where evidence appears")
    chunk_type: str = Field(..., description="Type of chunk (text, table, caption, header)")
    text: str = Field(..., description="Content of the evidence")
    relevance_score: float = Field(..., ge=0.0, le=1.0, description="Cosine relevance score to intent")


class KeyMetricItem(BaseModel):
    """Extracted numeric or factual metric for accurate quantitative generation."""
    label: str = Field(..., description="Description of the metric (e.g., 'Revenue Growth', 'Model Accuracy')")
    value: str = Field(..., description="Formatted value (e.g., '+24.5%', '99.4% F1')")
    context: Optional[str] = Field(default=None, description="Qualifying context or comparison")
    source_element_id: Optional[str] = Field(default=None, description="Evidence element ID")
    page: Optional[int] = Field(default=None, description="Page number")


class TableSummaryItem(BaseModel):
    """Summary of a structured table relevant to the user intent."""
    element_id: str = Field(..., description="Element ID of the table")
    page: int = Field(..., ge=1)
    caption: Optional[str] = Field(default=None)
    markdown_table: str = Field(..., description="Clean markdown table content")
    key_takeaway: Optional[str] = Field(default=None, description="Core analytical takeaway from the table")


class VisualInsightItem(BaseModel):
    """Visual asset analysis and key takeaway."""
    element_id: str = Field(..., description="Element ID of the chart/diagram/image")
    page: int = Field(..., ge=1)
    element_type: str = Field(..., description="figure, chart, or image")
    caption: Optional[str] = Field(default=None)
    image_path: Optional[str] = Field(default=None, description="Relative path to cropped visual asset")
    takeaway: str = Field(..., description="Descriptive summary or trend takeaway")


class ContentStrategy(BaseModel):
    """Strategic guidance generated by Qwen3-4B for the Content Orchestrator."""
    headline_hook: str = Field(..., description="Suggested hook or headline tailored to persona")
    key_themes: List[str] = Field(default_factory=list, description="Primary narrative themes")
    suggested_structure: List[str] = Field(default_factory=list, description="Recommended section/slide outline")
    recommended_cta: Optional[str] = Field(default=None, description="Suggested call-to-action")
    tone_guidelines: Optional[str] = Field(default=None, description="Stylistic directives for generation")


class KnowledgePackage(BaseModel):
    """
    Standardized Knowledge Context Payload.
    The primary output of the Knowledge & Retrieval Layer, passed directly to
    the Content Orchestrator (Phase 5).
    """
    version: str = Field(default="1.0.0", description="Schema version")
    document_id: str = Field(..., description="Target document ID")
    document_title: Optional[str] = Field(default=None, description="Document title or filename")
    intent: IntentAndPersonalization = Field(..., description="User intent and persona configuration")
    
    # Retrieved & Structured Semantic Context
    retrieved_evidence: List[EvidenceItem] = Field(
        default_factory=list,
        description="Top-ranked semantic evidence chunks with relevance scores"
    )
    entities: List[EntityItem] = Field(
        default_factory=list,
        description="Named entities recognized and verified for this topic"
    )
    claims: List[ClaimItem] = Field(
        default_factory=list,
        description="Verified factual propositions with source element traceability"
    )
    relationships: List[RelationshipItem] = Field(
        default_factory=list,
        description="Core semantic entity triples"
    )
    key_metrics: List[KeyMetricItem] = Field(
        default_factory=list,
        description="Quantitative metrics and statistics extracted from content"
    )
    tables: List[TableSummaryItem] = Field(
        default_factory=list,
        description="Relevant structured tables"
    )
    visual_insights: List[VisualInsightItem] = Field(
        default_factory=list,
        description="Visual assets (charts/diagrams) and their interpretations"
    )
    
    # LLM Synthesis & Strategic Blueprint
    strategy: ContentStrategy = Field(
        ...,
        description="High-level narrative structure and hook generated by Qwen3-4B"
    )
    
    # Pre-compiled high-density markdown context block for Orchestrator Prompt
    orchestrator_prompt_context: str = Field(
        ...,
        description="Pre-assembled high-density context block ready for injection into LLM prompts"
    )
    
    metadata: Dict[str, Any] = Field(
        default_factory=dict,
        description="Telemetry and processing metadata (e.g. token counts, retrieval latency)"
    )
